// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Telemetry.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_TELEMETRY_H_
#define _FAST_DDS_GENERATED_TELEMETRY_H_



#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(Telemetry_SOURCE)
#define Telemetry_DllAPI __declspec( dllexport )
#else
#define Telemetry_DllAPI __declspec( dllimport )
#endif // Telemetry_SOURCE
#else
#define Telemetry_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define Telemetry_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


/*!
 * @brief This class represents the structure SystemStats defined by the user in the IDL file.
 * @ingroup TELEMETRY
 */
class SystemStats
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport SystemStats();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~SystemStats();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object SystemStats that will be copied.
     */
    eProsima_user_DllExport SystemStats(
            const SystemStats& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object SystemStats that will be copied.
     */
    eProsima_user_DllExport SystemStats(
            SystemStats&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object SystemStats that will be copied.
     */
    eProsima_user_DllExport SystemStats& operator =(
            const SystemStats& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object SystemStats that will be copied.
     */
    eProsima_user_DllExport SystemStats& operator =(
            SystemStats&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x SystemStats object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const SystemStats& x) const;

    /*!
     * @brief Comparison operator.
     * @param x SystemStats object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const SystemStats& x) const;

    /*!
     * @brief This function sets a value in member packet_id
     * @param _packet_id New value for member packet_id
     */
    eProsima_user_DllExport void packet_id(
            uint32_t _packet_id);

    /*!
     * @brief This function returns the value of member packet_id
     * @return Value of member packet_id
     */
    eProsima_user_DllExport uint32_t packet_id() const;

    /*!
     * @brief This function returns a reference to member packet_id
     * @return Reference to member packet_id
     */
    eProsima_user_DllExport uint32_t& packet_id();

    /*!
     * @brief This function sets a value in member roll
     * @param _roll New value for member roll
     */
    eProsima_user_DllExport void roll(
            float _roll);

    /*!
     * @brief This function returns the value of member roll
     * @return Value of member roll
     */
    eProsima_user_DllExport float roll() const;

    /*!
     * @brief This function returns a reference to member roll
     * @return Reference to member roll
     */
    eProsima_user_DllExport float& roll();

    /*!
     * @brief This function sets a value in member pitch
     * @param _pitch New value for member pitch
     */
    eProsima_user_DllExport void pitch(
            float _pitch);

    /*!
     * @brief This function returns the value of member pitch
     * @return Value of member pitch
     */
    eProsima_user_DllExport float pitch() const;

    /*!
     * @brief This function returns a reference to member pitch
     * @return Reference to member pitch
     */
    eProsima_user_DllExport float& pitch();

    /*!
     * @brief This function sets a value in member yaw
     * @param _yaw New value for member yaw
     */
    eProsima_user_DllExport void yaw(
            float _yaw);

    /*!
     * @brief This function returns the value of member yaw
     * @return Value of member yaw
     */
    eProsima_user_DllExport float yaw() const;

    /*!
     * @brief This function returns a reference to member yaw
     * @return Reference to member yaw
     */
    eProsima_user_DllExport float& yaw();

    /*!
     * @brief This function sets a value in member altitude
     * @param _altitude New value for member altitude
     */
    eProsima_user_DllExport void altitude(
            float _altitude);

    /*!
     * @brief This function returns the value of member altitude
     * @return Value of member altitude
     */
    eProsima_user_DllExport float altitude() const;

    /*!
     * @brief This function returns a reference to member altitude
     * @return Reference to member altitude
     */
    eProsima_user_DllExport float& altitude();

    /*!
     * @brief This function sets a value in member speed
     * @param _speed New value for member speed
     */
    eProsima_user_DllExport void speed(
            float _speed);

    /*!
     * @brief This function returns the value of member speed
     * @return Value of member speed
     */
    eProsima_user_DllExport float speed() const;

    /*!
     * @brief This function returns a reference to member speed
     * @return Reference to member speed
     */
    eProsima_user_DllExport float& speed();

    /*!
     * @brief This function sets a value in member x
     * @param _x New value for member x
     */
    eProsima_user_DllExport void x(
            float _x);

    /*!
     * @brief This function returns the value of member x
     * @return Value of member x
     */
    eProsima_user_DllExport float x() const;

    /*!
     * @brief This function returns a reference to member x
     * @return Reference to member x
     */
    eProsima_user_DllExport float& x();

    /*!
     * @brief This function sets a value in member z
     * @param _z New value for member z
     */
    eProsima_user_DllExport void z(
            float _z);

    /*!
     * @brief This function returns the value of member z
     * @return Value of member z
     */
    eProsima_user_DllExport float z() const;

    /*!
     * @brief This function returns a reference to member z
     * @return Reference to member z
     */
    eProsima_user_DllExport float& z();

    /*!
     * @brief This function sets a value in member landing_mode
     * @param _landing_mode New value for member landing_mode
     */
    eProsima_user_DllExport void landing_mode(
            bool _landing_mode);

    /*!
     * @brief This function returns the value of member landing_mode
     * @return Value of member landing_mode
     */
    eProsima_user_DllExport bool landing_mode() const;

    /*!
     * @brief This function returns a reference to member landing_mode
     * @return Reference to member landing_mode
     */
    eProsima_user_DllExport bool& landing_mode();

    /*!
     * @brief This function sets a value in member system_active
     * @param _system_active New value for member system_active
     */
    eProsima_user_DllExport void system_active(
            bool _system_active);

    /*!
     * @brief This function returns the value of member system_active
     * @return Value of member system_active
     */
    eProsima_user_DllExport bool system_active() const;

    /*!
     * @brief This function returns a reference to member system_active
     * @return Reference to member system_active
     */
    eProsima_user_DllExport bool& system_active();

    /*!
     * @brief This function copies the value in member status_msg
     * @param _status_msg New value to be copied in member status_msg
     */
    eProsima_user_DllExport void status_msg(
            const std::string& _status_msg);

    /*!
     * @brief This function moves the value in member status_msg
     * @param _status_msg New value to be moved in member status_msg
     */
    eProsima_user_DllExport void status_msg(
            std::string&& _status_msg);

    /*!
     * @brief This function returns a constant reference to member status_msg
     * @return Constant reference to member status_msg
     */
    eProsima_user_DllExport const std::string& status_msg() const;

    /*!
     * @brief This function returns a reference to member status_msg
     * @return Reference to member status_msg
     */
    eProsima_user_DllExport std::string& status_msg();

    /*!
     * @brief This function returns the maximum serialized size of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function returns the serialized size of a data depending on the buffer alignment.
     * @param data Data which is calculated its serialized size.
     * @param current_alignment Buffer alignment.
     * @return Serialized size.
     */
    eProsima_user_DllExport static size_t getCdrSerializedSize(
            const SystemStats& data,
            size_t current_alignment = 0);


    /*!
     * @brief This function serializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serialize(
            eprosima::fastcdr::Cdr& cdr) const;

    /*!
     * @brief This function deserializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void deserialize(
            eprosima::fastcdr::Cdr& cdr);



    /*!
     * @brief This function returns the maximum serialized size of the Key of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function tells you if the Key has been defined for this type
     */
    eProsima_user_DllExport static bool isKeyDefined();

    /*!
     * @brief This function serializes the key members of an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serializeKey(
            eprosima::fastcdr::Cdr& cdr) const;

private:

    uint32_t m_packet_id;
    float m_roll;
    float m_pitch;
    float m_yaw;
    float m_altitude;
    float m_speed;
    float m_x;
    float m_z;
    bool m_landing_mode;
    bool m_system_active;
    std::string m_status_msg;
};

#endif // _FAST_DDS_GENERATED_TELEMETRY_H_